<a href="https://colab.research.google.com/github/justynababuchowska/data-science-bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install numpy

In [3]:
import numpy as np

Norma wektora, Długość wektora w R2

In [6]:
v1= np.array([-1, 4])
v1

array([-1,  4])

In [7]:
#oblicza długość wektora w przestrzeni 2wymiarowej
np.linalg.norm(v1)

4.123105625617661

Norma Euklidesowa w Rn

In [8]:
#przykładowo długość wejtora w przestrzeni R3
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

In [10]:
#odległośc 2 punktów w przestrzeni R2 - odejmujemy 2 wektory od siebie, a następnie standardowo liczymy długość
p= np.array([3,0])
q= np.array([0,4])

np.linalg.norm(p-q)

5.0

In [12]:
#odległość dwóch punktów w przestrzeni Rn
p= np.array([3,0, 1])
q= np.array([0,4, 2])

np.linalg.norm(p-q)

5.0990195135927845

Mnożenie macierzy - aby pomnożyć macierze liczba kolumn lewej macierzy musi być równa liczbie wierszy w prawej macierzy. Mnożenie macierzy nie jest przemienne!

In [15]:
X = np.array([[5,3],[3,9]])
Y= np.array([[1],[-1]])
print(X)
print(Y)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [16]:
#obliczamy macierz wynikową (nie można odwrotnie Y*X bo liczba kolumn wówczas nie zgadza się z liczbą wierszy)
Z= np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [18]:
Z = X.dot(Y)
Z

array([[ 2],
       [-6]])

In [19]:
Z = X @ Y
Z

array([[ 2],
       [-6]])

In [21]:
#przykład X macierz 2x3, Y macierz 3x3
X= np.array([[2, -1, 3],
            [3, 1, 0]])
Y=np.array([[2,1,-5],
            [1,5,7],
            [3,-5,0]])

Z = np.dot(X,Y)
Z

array([[ 12, -18, -17],
       [  7,   8,  -8]])

Wyznacznik macierzy

In [23]:
#liczymy wyznacznik macierzy - mnożymy po przekątnej i odejmujemy. Biblioteka np.linalg.det(X)
A = [[2,4],[-1,3]]
np.linalg.det(A)

9.999999999999998

In [24]:
#możemy zaokrąglić wynik
round(np.linalg.det(A))

10

Ślad macierzy - suma cyfr po przekątnej (od lewego górnego rogu)

In [55]:
A = [[2,4],[-1,3]]
np.trace(A)

5

Macierz jednostkowa -
macierz kwadratowa, w której wszystkie elementy na głównej przekątnej są równe 1, a wszystkie pozostałe elementy są równe 0
(mnożenie dowolnej macierzy przez macierz jednostkową nie zmienia wartości tej macierzy)

In [28]:
# tworzymy ją podając tylko 1parametr(kwadrat)
np.eye(5, dtype="int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [29]:
#domyslnie float
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Macierz odwrotna - to taka, która po pomnożeniu przez oryginalną macierz daje macierz jednostkową i musi być kwadratowa

*  AB=BA=I



In [32]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [33]:
#aby sprawdzić mnożymy macierze i dostajemy macierz jednostkową
np.dot(A,B)

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

In [39]:
#aby poprawić czytelność ustawiamy wydruk (miejsca po przecinku, zaokrągla nam małe wartości przy True)
np.set_printoptions(precision=4, suppress=True)
np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

In [40]:
np.dot(B,A)

array([[ 1., -0.],
       [ 0.,  1.]])

Macierz transponowana - zmiana wierszy na kolumny i kolumny na wiersze

In [41]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [ ]:
#inny prostszy zapis
A.T

Układy równań
A - macierz współczynników
X - wektor niewiadomych
B - wektor wyrazów wolnych (wynik)

mnożąc macierze AX=B

Jeśli macierz A jest kwadratowa to oznaczoność układu jest równa jej odwracalności:

AX=B

(A-1)AX=(A-1)B

X=(A-1)B

In [ ]:
"""
2x+4y=10
x-y=-1
"""
A = np.array([[2,4],[1,-1]])
B = np.array([[10],[-1]])

In [7]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv,B)
X

array([[1.],
       [2.]])