<a href="https://colab.research.google.com/github/justynababuchowska/data-science-bootcamp/blob/main/01_wprowadzenie/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Funkcje statystyczne

In [ ]:
price = np.array([[12.4, 12.8, 11.9, 12.6, 1000],
                 [12.5, 13.0, 11.7, 12.2, 2000],
                 [12.2, 13.4, 12.2, 13.2, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [ ]:
# sum() - suma wszystkich elementów
price.sum()

4650.1

In [ ]:
#suma w kolumnach ustawiamy axis =0
price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [ ]:
#suma w rzędach ustawiamy axis = 1
price.sum(axis=1)

array([1049.7, 2049.4, 1551. ])

In [ ]:
#za pomocą biblioteki np/ możemy bez axis lub analogicznie jak powyżej wstawić
np.sum(price, axis = 0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [9]:
#min()
np.min(price)

11.7

In [11]:
#analogicznie jeśli minimum w kolumnie axis = 0, w wierszu axis = 1
np.min(price, axis=0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [12]:
#max() - analogicznie w całości, kolumnie i wierszu
np.max(price, axis=1)

array([1000., 2000., 1500.])

In [13]:
#median()
np.median(price)

12.6

In [14]:
#mean() - średnia analogicznie całość lub kolumna/rząd
np.mean(price, axis=0)

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

In [16]:
#std() - odchylenie standardowe, również po kolumnach/rzędach
np.std(price, axis=0)

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

In [17]:
#var() - wariancja próbki danych
np.var(price, axis=0)

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])